export const dashboardMusicData = [
    // Músicas mais utilizadas - aparecem múltiplas vezes
    {
        musica: "We Will Rock You",
        efeitoSonoro: "Abertura",
        artista: "Queen",
        interprete: "Queen",
        gravadora: "EMI Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:00:30",
        isrc: "GBUM71029679",
        tempoTotal: "00:00:30",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "We Will Rock You",
        efeitoSonoro: "Abertura",
        artista: "Queen",
        interprete: "Queen",
        gravadora: "EMI Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:00:30",
        isrc: "GBUM71029679",
        tempoTotal: "00:00:30",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "We Will Rock You",
        efeitoSonoro: "Abertura",
        artista: "Queen",
        interprete: "Queen",
        gravadora: "EMI Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:00:30",
        isrc: "GBUM71029679",
        tempoTotal: "00:00:30",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Imagine",
        efeitoSonoro: "Dramático",
        artista: "John Lennon",
        interprete: "John Lennon",
        gravadora: "Apple Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:20",
        isrc: "USRC17607839",
        tempoTotal: "00:01:20",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Imagine",
        efeitoSonoro: "Dramático",
        artista: "John Lennon",
        interprete: "John Lennon",
        gravadora: "Apple Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:20",
        isrc: "USRC17607839",
        tempoTotal: "00:01:20",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Bohemian Rhapsody",
        efeitoSonoro: "Encerramento",
        artista: "Queen",
        interprete: "Freddie Mercury",
        gravadora: "EMI Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:15",
        isrc: "GBUM71029680",
        tempoTotal: "00:02:15",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Bohemian Rhapsody",
        efeitoSonoro: "Encerramento",
        artista: "Queen",
        interprete: "Freddie Mercury",
        gravadora: "EMI Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:15",
        isrc: "GBUM71029680",
        tempoTotal: "00:02:15",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Hotel California",
        efeitoSonoro: "Transição",
        artista: "Eagles",
        interprete: "Eagles",
        gravadora: "Asylum Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:45",
        isrc: "USRC17607840",
        tempoTotal: "00:01:45",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Hotel California",
        efeitoSonoro: "Transição",
        artista: "Eagles",
        interprete: "Eagles",
        gravadora: "Asylum Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:45",
        isrc: "USRC17607840",
        tempoTotal: "00:01:45",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Stairway to Heaven",
        efeitoSonoro: "Dramático",
        artista: "Led Zeppelin",
        interprete: "Led Zeppelin",
        gravadora: "Atlantic Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:30",
        isrc: "USRC17607841",
        tempoTotal: "00:02:30",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Sweet Child O' Mine",
        efeitoSonoro: "Abertura",
        artista: "Guns N' Roses",
        interprete: "Guns N' Roses",
        gravadora: "Geffen Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:30",
        isrc: "USRC17607842",
        tempoTotal: "00:01:30",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Sweet Child O' Mine",
        efeitoSonoro: "Abertura",
        artista: "Guns N' Roses",
        interprete: "Guns N' Roses",
        gravadora: "Geffen Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:30",
        isrc: "USRC17607842",
        tempoTotal: "00:01:30",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Don't Stop Believin'",
        efeitoSonoro: "Encerramento",
        artista: "Journey",
        interprete: "Journey",
        gravadora: "Columbia Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:00",
        isrc: "USRC17607843",
        tempoTotal: "00:02:00",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Billie Jean",
        efeitoSonoro: "Transição",
        artista: "Michael Jackson",
        interprete: "Michael Jackson",
        gravadora: "Epic Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:45",
        isrc: "USRC17607844",
        tempoTotal: "00:01:45",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Billie Jean",
        efeitoSonoro: "Transição",
        artista: "Michael Jackson",
        interprete: "Michael Jackson",
        gravadora: "Epic Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:01:45",
        isrc: "USRC17607844",
        tempoTotal: "00:01:45",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Smells Like Teen Spirit",
        efeitoSonoro: "Dramático",
        artista: "Nirvana",
        interprete: "Nirvana",
        gravadora: "DGC Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:15",
        isrc: "USRC17607845",
        tempoTotal: "00:02:15",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Smells Like Teen Spirit",
        efeitoSonoro: "Dramático",
        artista: "Nirvana",
        interprete: "Nirvana",
        gravadora: "DGC Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:15",
        isrc: "USRC17607845",
        tempoTotal: "00:02:15",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Smells Like Teen Spirit",
        efeitoSonoro: "Dramático",
        artista: "Nirvana",
        interprete: "Nirvana",
        gravadora: "DGC Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:15",
        isrc: "USRC17607845",
        tempoTotal: "00:02:15",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Wonderwall",
        efeitoSonoro: "Encerramento",
        artista: "Oasis",
        interprete: "Oasis",
        gravadora: "Creation Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:00",
        isrc: "GBUM71029681",
        tempoTotal: "00:02:00",
        imagemReportagem: "/api/placeholder/300/200"
    },
    {
        musica: "Wonderwall",
        efeitoSonoro: "Encerramento",
        artista: "Oasis",
        interprete: "Oasis",
        gravadora: "Creation Records",
        tempoInicio: "00:00:00",
        tempoFim: "00:02:00",
        isrc: "GBUM71029681",
        tempoTotal: "00:02:00",
        imagemReportagem: "/api/placeholder/300/200"
    }
];
